# Generated by Django 5.2.15 on 2026-06-11 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_twofactordevice_twofactorrecoverycode_authtoken_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twofactordevice',
            name='secret',
            field=models.CharField(max_length=255),
        ),
    ]
