# Generated by Django 5.2.15 on 2026-06-11 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_twofactordevice_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='actor_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='request_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user_agent',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['actor_type', 'actor_id'], name='api_audit_actor_type_id_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['request_id'], name='api_audit_request_id_idx'),
        ),
    ]
