# Generated by Django 5.2.15 on 2026-06-11 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_plan_stripe_price_id_alter_subscription_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
