# Generated by Django 5.2.15 on 2026-06-11 17:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_organization_stripe_customer_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSecret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('active', 'Active'), ('deleted', 'Deleted')], default='active', max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('current_version', models.PositiveIntegerField(default=1)),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_project_secrets', to=settings.AUTH_USER_MODEL)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secrets', to='api.environment')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_secrets', to='api.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secrets', to='api.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectSecretVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField()),
                ('encrypted_value', models.TextField()),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_project_secret_versions', to=settings.AUTH_USER_MODEL)),
                ('secret', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='api.projectsecret')),
            ],
        ),
        migrations.AddIndex(
            model_name='projectsecret',
            index=models.Index(fields=['organization', 'project', 'environment', 'status'], name='api_secret_scope_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='projectsecret',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('environment', 'name'), name='uniq_active_secret_env_name'),
        ),
        migrations.AddIndex(
            model_name='projectsecretversion',
            index=models.Index(fields=['secret', '-version'], name='api_secret_version_idx'),
        ),
        migrations.AddConstraint(
            model_name='projectsecretversion',
            constraint=models.UniqueConstraint(fields=('secret', 'version'), name='uniq_secret_version'),
        ),
    ]
