# Generated by Django 5.2.15 on 2026-06-12 14:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_notificationmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='anonymized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DataDeletionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope', models.CharField(choices=[('user', 'User'), ('organization', 'Organization')], max_length=32)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('soft_deleted', 'Soft deleted'), ('hard_deleted', 'Hard deleted'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='requested', max_length=32)),
                ('retention_until', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_deletion_requests', to='api.organization')),
                ('requested_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_deletion_requests', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_deletion_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['scope', 'status', 'retention_until'], name='api_delete_scope_status_idx'), models.Index(fields=['organization', 'status'], name='api_delete_org_status_idx'), models.Index(fields=['target_user', 'status'], name='api_delete_user_status_idx')],
            },
        ),
        migrations.CreateModel(
            name='DataExportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope', models.CharField(choices=[('user', 'User'), ('organization', 'Organization')], max_length=32)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('expired', 'Expired')], default='queued', max_length=32)),
                ('file_path', models.CharField(blank=True, max_length=1024)),
                ('file_sha256', models.CharField(blank=True, max_length=64)),
                ('download_token_hash', models.CharField(blank=True, max_length=255)),
                ('download_expires_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('failed_reason', models.CharField(blank=True, max_length=255)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_export_requests', to='api.organization')),
                ('requested_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_export_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['requested_by_user', '-created_at'], name='api_export_user_created_idx'), models.Index(fields=['organization', '-created_at'], name='api_export_org_created_idx'), models.Index(fields=['status', 'download_expires_at'], name='api_export_status_exp_idx')],
            },
        ),
    ]
