apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.project.namespace | quote }}
  labels:
    app.kubernetes.io/managed-by: provisioner
    platform.example.com/organization-id: {{ .Values.project.organizationId | quote }}
    platform.example.com/project-id: {{ .Values.project.projectId | quote }}
    platform.example.com/environment-id: {{ .Values.project.environmentId | quote }}
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
