apiVersion: v1
kind: ResourceQuota
metadata:
  name: project-quota
  namespace: {{ .Values.project.namespace | quote }}
spec:
  hard:
    requests.cpu: {{ .Values.quota.requestsCpu | quote }}
    requests.memory: {{ .Values.quota.requestsMemory | quote }}
    limits.cpu: {{ .Values.quota.limitsCpu | quote }}
    limits.memory: {{ .Values.quota.limitsMemory | quote }}
    pods: {{ .Values.quota.pods | quote }}
---
apiVersion: v1
kind: LimitRange
metadata:
  name: project-limits
  namespace: {{ .Values.project.namespace | quote }}
spec:
  limits:
    - type: Container
      default:
        cpu: {{ .Values.resources.limits.cpu | quote }}
        memory: {{ .Values.resources.limits.memory | quote }}
      defaultRequest:
        cpu: {{ .Values.resources.requests.cpu | quote }}
        memory: {{ .Values.resources.requests.memory | quote }}
